pipeline {
    agent any

    environment {
        GIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
    }

    stages {
        stage('Get Dockerfile') {
            steps {
                sh "curl -O https://gitlab.rero.ch/rero21/reroils-data/raw/master/development/Dockerfile"
                sh "curl -O https://gitlab.rero.ch/rero21/reroils-data/raw/master/development/build_app.sh"
            }
        }
       
        stage('Build Test Docker Image') {
                steps {
                    echo 'Building..'
                    script {
                        app_dev = docker.build('rero/reroils-data:test', '--rm  -f Dockerfile .')
                    }
                }
        }
        stage('Run Test') {
            steps {
                script {
                   sh "docker run --rm rero/reroils-data:test"
                }
            }
        }

        stage('Cleaning') {
                steps {
                    echo 'Cleaning....'
                    script {
                        sh "docker rmi rero/reroils-data:test"
                    }
                }
         }
    }
}
